# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL?=adc_analog
VERILOG_SOURCES?=$(BASE)/rtl/adc/adc_analog_model.sv


# include common makefile that gathers common attributes
include $(BASE)/tb_common/Makefile.common

