# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL?=counter_4bit
VERILOG_SOURCES?=$(BASE)/rtl/counter/counter_4bit_halfadder.sv $(BASE)/rtl/counter/dff.sv $(BASE)/rtl/counter/halfadder.sv


# include common makefile that gathers common attributes
include $(BASE)/tb_common/Makefile.common

